### ISSUE TITLE
Supposed Syntax Error On Line 71 When Running Partial

### ISSUE THREAD

**Issue by axzolon** [cedws/discord-delete#15]
When attempting to run the code in Powershell on Windows, I get a Syntax Error:

```
python :   File "C:\Users\[user]\Downloads\discord-delete-master\discord_delete.py", line 71
At line:1 char:1
+ python C:\Users\[user]\Downloads\discord-delete-master\discord_delete. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (  File "C:\User...te.py", line 71:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
    async def __aenter__(self):
            ^
SyntaxError: invalid syntax

```

**Comment by cedws** [comment]
What is the output of `python --version`? I have a feeling you're running Python 2. You'll need Python 3.

**Comment by axzolon** [comment]
So I've switched to Python 3.7, however now I'm getting the following error
```
C:\Users\[user]\Downloads\discord-delete-master\discord_delete.py partial
Traceback (most recent call last):
  File "C:\Users\[user]\Downloads\discord-delete-master\discord_delete.py", line 11, in <module>
    from aiohttp import ClientSession
ModuleNotFoundError: No module named 'aiohttp'
```

**Comment by cedws** [comment]
You need to install the required Python modules (`pip install -r requirements.txt`). Please follow one of the [wiki](https://github.com/c-edw/discord-delete/wiki) guides.

**Comment by axzolon** [comment]
After much work, I finally got it to work. Thank you very much.
